sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g yarn codecov
script:
  - yarn test -- --coverage
  - codecov
  - yarn run build
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
