sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^3
install:
  - npm i
  - npm install -g codecov
before_script:
  - npm prune
script:
  - npm test -- --coverage
  - codecov
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
