sudo: false
language: node_js
cache:
  directories:
    - ~/.yarn-cache
notifications:
  email: false
node_js:
  - '6'
  - node
before_install:
  - npm i -g yarn codecov
install:
  - yarn
script:
  - yarn test -- --coverage
  - codecov
  - yarn run build
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
