name: 'Install, Lint, Unit test, Build'

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install and cache the build
      - uses: bahmutov/npm-install@v1

      # Cache the entire working directory for subsequent steps
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

  typeCheck:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn tsc

  codeLinter:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn lint
      - run: yarn check-format

  jestUnitTests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn jest
        env:
          CI: true

  nextjsBuild:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      # Build the next.js app
      - run: yarn build
        env:
          API_URL: ${{ secrets.API_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
