name: 'Install, Lint, Unit test, Build, run Cypress tests'

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install and cache the build
      - uses: bahmutov/npm-install@v1

      # Cache the entire working directory for subsequent steps
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

  typeCheck:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn tsc

  codeLinter:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn lint
      - run: yarn check-format

  jestUnitTests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - run: yarn jest
        env:
          CI: true

  cypressIntegration:
    needs: [codeLinter, jestUnitTests, nextJsBuild] # only run if these all pass
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      matrix:
        backend: [dev-latest] # keep as a matrix strategy for times we want to test against an additional specific build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ github.sha }}

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        id: jar-cache
        with:
          path: ${{ matrix.backend }}.jar
          key: ${{ matrix.backend }}.jar

      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - run: yarn build

      - if: steps.jar-cache.outputs.cache-hit != 'true'
        run: curl https://r5-builds.s3-eu-west-1.amazonaws.com/${{ matrix.backend }}.jar --output ${{ matrix.backend }}.jar

      - uses: cypress-io/github-action@v2
        with:
          # passed to the cypress cli command
          env: ${{ secrets.CYPRESS_GITHUB_ENV }}
          spec: cypress/integration/local/all.js
          start: yarn action
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
        env:
          NEXT_PUBLIC_BASEMAP_DISABLED: true
          NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
